require('dotenv').config();
const request = require('supertest');
const app = require('../src/app');
const supabase = require('../src/lib/supabase');

let token;
let studentId;
let parentToken;
let scheduleId;
let attendanceId;
let paymentId;

beforeAll(async () => {
  const loginRes = await request(app)
    .post('/api/auth/login')
    .send({ email: process.env.COACH_EMAIL, password: process.env.COACH_PASSWORD });
  token = loginRes.body.token;

  // Create test student (parent_access_token auto-generated by Supabase default)
  const stuRes = await supabase.from('students').insert({
    name: 'Dashboard Test Student', date_of_birth: '2014-01-01',
    skill_level: 'Beginner', parent_name: 'Dash Parent',
    parent_phone: '555-4444', parent_email: 'dash@test.com',
  }).select().single();
  studentId = stuRes.data.id;
  parentToken = stuRes.data.parent_access_token;

  // Create a schedule 3 days in the future (within 14-day window)
  const futureDate = new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
  const schedRes = await supabase.from('schedules').insert({
    date: futureDate, time: '10:00', duration_minutes: 60,
    location: 'Dash Court', age_category: 'U13', fee: 20,
  }).select().single();
  scheduleId = schedRes.data.id;

  // Mark student as present
  const attRes = await supabase.from('attendance').insert({
    schedule_id: scheduleId, student_id: studentId,
    status: 'present', checked_in_at: new Date().toISOString(),
  }).select().single();
  attendanceId = attRes.data.id;

  // Record a partial payment ($10 of $20 owed)
  const payRes = await supabase.from('payments').insert({
    student_id: studentId, amount: 10,
    payment_date: new Date().toISOString().slice(0, 10),
  }).select().single();
  paymentId = payRes.data.id;
});

afterAll(async () => {
  if (paymentId) await supabase.from('payments').delete().eq('id', paymentId);
  if (attendanceId) await supabase.from('attendance').delete().eq('id', attendanceId);
  if (scheduleId) await supabase.from('schedules').delete().eq('id', scheduleId);
  if (studentId) await supabase.from('students').delete().eq('id', studentId);
});

const auth = () => ({ Authorization: `Bearer ${token}` });

describe('GET /api/dashboard', () => {
  it('returns 401 without auth', async () => {
    const res = await request(app).get('/api/dashboard');
    expect(res.status).toBe(401);
  });

  it('returns upcoming_sessions and student_balances arrays', async () => {
    const res = await request(app).get('/api/dashboard').set(auth());
    expect(res.status).toBe(200);
    expect(Array.isArray(res.body.upcoming_sessions)).toBe(true);
    expect(Array.isArray(res.body.student_balances)).toBe(true);
  });

  it('includes the upcoming test session', async () => {
    const res = await request(app).get('/api/dashboard').set(auth());
    const found = res.body.upcoming_sessions.find(s => s.id === scheduleId);
    expect(found).toBeDefined();
  });

  it('includes the student with outstanding balance', async () => {
    const res = await request(app).get('/api/dashboard').set(auth());
    const found = res.body.student_balances.find(s => s.id === studentId);
    expect(found).toBeDefined();
    expect(found.balance).toBe(10); // $20 owed − $10 paid
  });
});

describe('GET /api/parent/:token', () => {
  it('returns student data without auth header', async () => {
    const res = await request(app).get(`/api/parent/${parentToken}`);
    expect(res.status).toBe(200);
    expect(res.body.student.name).toBe('Dashboard Test Student');
    expect(Array.isArray(res.body.sessions)).toBe(true);
    expect(Array.isArray(res.body.payments)).toBe(true);
    expect(res.body).toHaveProperty('summary');
  });

  it('does not expose sensitive student fields', async () => {
    const res = await request(app).get(`/api/parent/${parentToken}`);
    expect(res.body.student).not.toHaveProperty('parent_phone');
    expect(res.body.student).not.toHaveProperty('parent_email');
    expect(res.body.student).not.toHaveProperty('parent_access_token');
  });

  it('returns 404 for invalid token', async () => {
    const res = await request(app).get('/api/parent/00000000-0000-0000-0000-000000000000');
    expect(res.status).toBe(404);
  });

  it('computes correct totals', async () => {
    const res = await request(app).get(`/api/parent/${parentToken}`);
    expect(res.body.summary.total_owed).toBe(20);
    expect(res.body.summary.total_paid).toBe(10);
    expect(res.body.summary.balance).toBe(10);
  });
});
